export const SYSTEM_FONTS = new Set([
	"Arial",
	"Helvetica",
	"Times New Roman",
	"Courier New",
	"Verdana",
	"Georgia",
	"Microsoft YaHei",
	"Microsoft YaHei UI",
	"SimSun",
	"NSimSun",
	"SimHei",
	"KaiTi",
	"FangSong",
	"DengXian",
	"Microsoft JhengHei",
	"Noto Sans SC",
	"Noto Serif SC",
	"monospace",
	"sans-serif",
	"serif",
]);
